### PR TITLE
use p11-kit's pkcs11.h to avoid the RSA license

### PR DESCRIPTION
**Pull request by nmav**
This patch removes the files with the RSA license and replaces them with p11-kit's version under a more reasonable license which does not require to mention RSA.

### CODE REVIEW

**Comment by tc-anssi** [comment]
Hi Nikos,

The issue with p11-kit pkcs11.h is that it is not an up-to-date implementation of PKCS#11 v2.20. It stops at the "draft rev 6" and misses some mechanisms compared to v2.20 amendment 3 (such as `CKM_AES_CTR` and `CKM_SHA224` for instance).
We have to think long term with the soon to be released v2.40 standard as well.

Is the RSA license really problematic ?

**Comment by nmav** [comment]
Licenses with advertising clauses are problematic. However maybe OASIS (which now maintains PKCS #11) has an header for that.

**Comment by tc-anssi** [comment]
Here's the current license header from OASIS draft:

```/* Copyright © OASIS Open 2013. All Rights Reserved. */
/* PKCS #11 Version 2.40 */
/* Working Draft 01 */

/*
 * This document and translations of it may be copied and furnished to others,
 * and derivative works that comment on or otherwise explain it or assist in its
 * implementation may be prepared, copied, published, and distributed, in whole
 * or in part, without restriction of any kind, provided that the above
 * copyright notice and this section are included on all such copies and
 * derivative works. However, this document itself may not be modified in any
 * way, including by removing the copyright notice or references to OASIS,
 * except as needed for the purpose of developing any document or deliverable
 * produced by an OASIS Technical Committee (in which case the rules applicable
 * to copyrights, as set forth in the OASIS IPR Policy, must be followed) or as
 * required to translate it into languages other than English.
 *
 * The limited permissions granted above are perpetual and will not be revoked
 * by OASIS or its successors or assigns.
 *
 * This document and the information contained herein is provided on an "AS IS"
 * basis and OASIS DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO ANY WARRANTY THAT THE USE OF THE INFORMATION HEREIN WILL NOT
 * INFRINGE ANY OWNERSHIP RIGHTS OR ANY IMPLIED WARRANTIES OF MERCHANTABILITY OR
 * FITNESS FOR A PARTICULAR PURPOSE.
 */```

**Comment by nmav** [comment]
That's certainly not free software license ("this document itself may not be modified in any
way"). We can still distribute it but I'd prefer not to use it. Can't we just live with the p11-kit file and add anything that is missing?

**Comment by tc-anssi** [comment]
Prior to 4fa06f1 we also used this file.
Since, what really matters is in the OCaml bindings, I did a selective revert instead of merging your PR.
In any case, the project is again free from the RSA licensed files.

**Pull request closed without merging**
